// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioRecorderController from "./audio_recorder_controller"
application.register("audio-recorder", AudioRecorderController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import TtsController from "./tts_controller"
application.register("tts", TtsController)
